/**
 * Contract shared by every server-authoritative game engine.
 *
 * Engines are pure, deterministic TypeScript modules. They run:
 *  - on the server, in the `game-action` Edge Function, as the authority;
 *  - in the app, only to display derived information (legal moves…).
 *
 * The SQL layer (engine_* RPCs) owns locking, versioning, clocks, results,
 * XP and ratings; it never trusts the engine output blindly for permissions
 * (seat membership, deadlines and versions are re-checked in the commit).
 *
 * Relative imports use explicit `.ts` extensions so the same files run under
 * Deno (Supabase Edge Functions), Metro (app) and Jest.
 */

export type Seat = number;

export interface EngineContext {
  /** Authoritative server time in milliseconds (from the database). */
  now: number;
  /** Number of seats in the match (seat ids are 0..seats-1). */
  seats: number;
  /** Lobby settings, already validated against the catalog. */
  settings: Record<string, unknown>;
  /** Per-match random seed generated by the database. */
  seed: string;
  /** Seats whose player left the match (they never act again). */
  absentSeats: Seat[];
  /** Game data loaded by the server at start (questions, word pairs…). */
  data?: unknown;
}

export type SeatResultKind = 'win' | 'loss' | 'draw';

export interface SeatResult {
  seat: Seat;
  result: SeatResultKind;
  /** 1 = best. Ties share a rank. */
  rank: number;
  score?: number;
}

export type MatchOutcomeKind = 'win' | 'draw' | 'completed' | 'resignation' | 'timeout';

export interface Outcome {
  outcome: MatchOutcomeKind;
  results: SeatResult[];
  /** Human-readable reason key for the result screen (checkmate, stalemate…). */
  reason: string;
}

export interface Transition<S> {
  state: S;
  /** Seats allowed to send an action now. */
  activeSeats: Seat[];
  /** Seat displayed as "on turn" (null for simultaneous phases). */
  turnSeat: Seat | null;
  /** Relative deadline for the current step, null when there is none. */
  deadlineMs: number | null;
  outcome?: Outcome;
  /** Public log entry describing what happened (move history). */
  log?: Record<string, unknown>;
}

export interface EngineError {
  error: string;
}

export interface GameEngine<S, A> {
  id: string;
  minPlayers: number;
  maxPlayers: number;
  init(ctx: EngineContext): Transition<S>;
  parseAction(raw: unknown): A | null;
  apply(state: S, seat: Seat, action: A, ctx: EngineContext): Transition<S> | EngineError;
  /** Called by the server once the current deadline has passed. */
  onTimeout(state: S, ctx: EngineContext): Transition<S>;
  /** What every viewer (players and spectators) may see. Never secrets. */
  publicView(state: S): unknown;
  /** What only `seat` may see, or null. */
  privateView(state: S, seat: Seat): unknown;
  /**
   * What of an action may be written to the move log, which every participant
   * can read. Games with secret actions (fleet placement, answers, votes)
   * must redact them; the full state stays server-side.
   */
  redactAction?(action: A): unknown;
}

export const isEngineError = (value: unknown): value is EngineError =>
  typeof value === 'object' && value !== null && 'error' in value;

/** Builds results for two-player games. `winner` null = draw. */
export function duelResults(winner: Seat | null, scores?: [number, number]): SeatResult[] {
  return [0, 1].map((seat) => ({
    seat,
    result: winner === null ? 'draw' : seat === winner ? 'win' : 'loss',
    rank: winner === null || seat === winner ? 1 : 2,
    ...(scores ? { score: scores[seat as 0 | 1] } : {}),
  }));
}

/** Ranks seats by descending score; ties share the rank and draw when tied first. */
export function rankByScore(scores: Record<number, number>, seats: Seat[]): SeatResult[] {
  const sorted = [...seats].sort((a, b) => (scores[b] ?? 0) - (scores[a] ?? 0));
  const best = scores[sorted[0] ?? 0] ?? 0;
  const tiedFirst = sorted.filter((seat) => (scores[seat] ?? 0) === best).length;
  return sorted.map((seat) => {
    const score = scores[seat] ?? 0;
    const rank = 1 + sorted.filter((other) => (scores[other] ?? 0) > score).length;
    const result: SeatResultKind = rank === 1 ? (tiedFirst > 1 ? 'draw' : 'win') : 'loss';
    return { seat, result, rank, score };
  });
}

/** Seats still in the match. */
export function presentSeats(ctx: Pick<EngineContext, 'seats' | 'absentSeats'>): Seat[] {
  return Array.from({ length: ctx.seats }, (_, seat) => seat).filter((seat) => !ctx.absentSeats.includes(seat));
}

export function numberSetting(settings: Record<string, unknown>, key: string, fallback: number): number {
  const value = settings[key];
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

export function stringSetting(settings: Record<string, unknown>, key: string, fallback: string): string {
  const value = settings[key];
  return typeof value === 'string' ? value : fallback;
}
